topic:
  name: topic-orders

server:
  port: 8181

spring:
  kafka:
    bootstrap-servers: "192.168.90.95:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://192.168.90.95:8081"
    consumer:
      group-id: "order-service-consumer-group"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "http://192.168.90.95:8081"
        specific:
          avro:
            reader: "true"